{"historyId": "29112f5860cd36ad5a56a5c55c2dbfc8", "links": [{"name": "搜索功能", "url": "搜索功能", "type": "test_case"}], "start": 1666322920498, "labels": [{"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "searchTest"}, {"name": "host", "value": "DESKTOP-2N4CHJQ"}, {"name": "thread", "value": "25812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.searchTest"}], "testCaseId": "97ed200b7629516bbb23d3c2d518fd1f", "uuid": "95d5964a-7114-4103-9d49-2388c9bdfda0", "parameters": [{"name": "test_data", "value": "'selenium'"}], "name": "test_SearchFun[selenium]", "stop": 1666322920498, "fullName": "cases.searchTest#test_SearchFun", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'help.yaml'", "trace": "test_data = 'selenium'\n\n    @allure.testcase(\"搜索功能\")\n    @pytest.mark.parametrize('test_data',['selenium','allure'])\n    def test_SearchFun(test_data):\n    \n>       with open(\"help.yaml\", encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'help.yaml'\n\nsearchTest.py:14: FileNotFoundError"}, "status": "broken"}